project:
  type: website
  output-dir: docs
  resources:
    - assets/

website:
  title: "안준현(An JunHyun) site"
  site-url: "https://anjunhyun.github.io/anjunhyun"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: seminar.qmd
        text: Seminar
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/anjunhyun
      - icon: envelope
        href: mailto:anjunhyun@snu.ac.kr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
